### ISSUE TITLE
As a user I want content to autoupdate so that I always get the latest version.

### ISSUE THREAD

**Issue by yuri** [rangle/treillage#1]
As a user I want content to autodeploy so that I always get the latest version.

Acceptance criteria:

* There needs to be a URL that gets automatically updated when a pull request is merged in master.
* This should be done via CircleCI (unless there is a good reason to do it differently).
* CircleCI should run tests and linting on each pull request.

**Comment by schoettler** [comment]
Generating a hased URL is not necessary, as webpack should be generating hashed bundles that won't be cached by the browser

**Comment by schoettler** [comment]
Also, moved node to version 6, since it's [the latest LTS version](https://github.com/nodejs/LTS)

**Comment by yuri** [comment]
@schoettler Where does it autodeploy to?

**Comment by schoettler** [comment]
Need creds for robot@rangle.io to configure auto-deployment with a [machine user](https://circleci.com/docs/1.0/github-security-ssh-keys/#machine-user-keys) instead of my personal Github account

**Comment by schoettler** [comment]
https://github.com/ranglebot needs access to the treillage project
