### ISSUE TITLE
As the editor I want people's names to be spelled correctly and wikilinked.

### ISSUE THREAD

**Issue by yuri** [rangle/treillage#10]
One of the most common mistakes in news items is misspelt names. We need to add validation rules that fix this.

Acceptance criteria:

- The validator should look for exact and close matches to names of people at Rangle.
- The validator should require exact matches to be wikilinked.
- The validator should warn the user about close matches (likely misspellings) and suggest possible corrections.
- The validator should catch the cases where only first names or nicknames (e.g., "DvR", "JLo") are used and should suggest that those should be replaced with a "|" style wikilink, e.g. "[[DvR|David van Rees]]").

**Comment by schoettler** [comment]
I have implemented this on Friday, but did not merge.

The reason is, performance.

I naturally went ahead with a n^2 function, iterating words in a sentence vs names. Increasingly bad for load time (If we had access to a buffer, we could filter in real time).

I'm working on optimizing this, filtering words with length < 3, also doing a prior regex lookup on the names dictionary.

**Comment by schoettler** [comment]
Another bit of complexity is, full names.

Would be nice to have a way to successfully filter out other words, for now I'm assuming any name is capitalized, (even nicknames). Do we want to validate full names, first + last or either?

**Comment by yuri** [comment]
@schoettler: Let's try to figure out what would be our MVP for this feature. Here are a few ways to reduce complexity as a starting point that come to mind:

- Only check capitalized words.
- Only check the cases where we have two or three capitalized words in a row or two capitalized words separated by a non-capitalized ones. (Effectively, only spellcheck first + last, but allowing for "van", "da", etc.)
- Do this check server side and memoize items.
- Move the processing to Amazon Lambda, each function call processing a separate item.

Maybe try the first two options and see if this brings performance to a sensible level. If not, let's try the server-side approach.

Another option to consider: processing one item at a time, updating the check status after each item. It might still take a few seconds to do the processing, but the user won't necessarily be impaired.
