### ISSUE TITLE
As the editor-in-chief, I want people to stick with a single paragraph for their items.

### ISSUE THREAD

**Issue by yuri** [rangle/treillage#11]
To facilitate reading, I want items to be short and fit in one paragraph. I want people to be warned when they don't do this properly.

Acceptance criteria:

- The validator should fail for any item that includes a new line.
- The validator should provide a helpful explanation and suggest that the user might want to link to a longer document.

**Comment by schoettler** [comment]
Link to a longer document?

**Comment by yuri** [comment]
If someone has something that takes more than 100 words to express, they
can create a document about this (in Google docs, a page in the wiki, etc)
and provide a link. Treillage doesn't need to do this, just provide the
suggestion.
-- 
*Yuri Takhteyev, CTO*
RANGLE.IO* – *Rewriting the Web

Connect on Twitter <https://twitter.com/rangleio> | LinkedIn
<http://www.linkedin.com/company/5018494> | Google+
<https://plus.google.com/b/102554894565578160295/102554894565578160295/posts>
 | Facebook <https://www.facebook.com/pages/Rangleio/229455467255298>
Read our latest blog post <http://rangle.io/blog/>

**Comment by schoettler** [comment]
Kyle reported on false flags for multiple paragraphs, refining the rule to detect:
<paragraph> line/break <paragraph> instead of just line breaks.
