### ISSUE TITLE
As the editor, I want the validator to detect items with no body.

### ISSUE THREAD

**Issue by yuri** [rangle/treillage#12]
Right now items that have no content in the body pass the validation checks. They should fail.

**Comment by schoettler** [comment]
Should they fail or not be shown at all?

**Comment by yuri** [comment]
They should show as failing validation.
-- 
*Yuri Takhteyev, CTO*
RANGLE.IO* – *Rewriting the Web

Connect on Twitter <https://twitter.com/rangleio> | LinkedIn
<http://www.linkedin.com/company/5018494> | Google+
<https://plus.google.com/b/102554894565578160295/102554894565578160295/posts>
 | Facebook <https://www.facebook.com/pages/Rangleio/229455467255298>
Read our latest blog post <http://rangle.io/blog/>
