### ISSUE TITLE
App overhaul: Webpack, Store & App state

### ISSUE THREAD

**Issue by schoettler** [rangle/treillage#25]
Webpack 2 offers faster bundles, also good to include the Redux Dev Tools, which are more featured than `redux-logger`.

Perhaps also modernize async/side effects from [redux-thunk](https://github.com/gaearon/redux-thunk) to something such as [MobX](https://github.com/mobxjs/mobx), instead of having a `R.pipe`, we can have a chain of independent, modular observables. This way, when Trello fails requests we can react properly, avoiding an infinite mysterious loading animation.

The validation messages are scalating rapidly, I have silently introduced `options` for rule output such as `ignorable`, in case the spellchecker is wrong and blocks the editor's approval.

Validation messages should be part of the state, as well as the content.

Working branch is: https://github.com/rangle/treillage/tree/feature/treillage-25

**Comment by yuri** [comment]
No MobX please. Redux observable would be fine, though I am not sure if there is enough complexity to justify this.

**Comment by schoettler** [comment]
1. Added Dev Tools.
2. Managing promises with `redux-thunk`, also we're showing failed async actions errors as feedback to the users.
3. Rules will remain as a service separated from the state: Sole responsibility is to flag cards. To manage the broken links, simply [[ names ]] not found in the dictionary will be flagged as broken wiki links (source of truth becomes important).
