### ISSUE TITLE
As the editor, I want to know if contributors have validated their cards so that can harass those who haven't.

### ISSUE THREAD

**Issue by yuri** [rangle/treillage#3]
There should be a mechanism for updating the card upon successful validation in Treillage. This would be ideally done using a custom field (I created one called "Validated in Preview") but if this field can't be updated through the API, then maybe posting a comment on the card would do.

Acceptance criteria:

* Each previewed item in Treillage should have a button next to it that says "Looks good!".
* The button should only be enabled if the item passed all the validations imposed by Treillage.
* Clicking the button should update the card in Trello, either setting the custom field to "Validated on {DATE}" or by posting a comment on the card.

**Comment by yuri** [comment]
@schoettler This seems to be working, but the UI seems a little confusing because the button doesn't really look like a button, so "Looks good!" reads as a statement made by validator rather than a call to action. Let's change it to "Confirm". Apart from that I think we can consider this done.

**Comment by schoettler** [comment]
I'll call it "Approve"

**Comment by yuri** [comment]
This seemed to work a bit back, but right now it seems like it no longer leaves comments on the trello cards.

**Comment by schoettler** [comment]
Fixed
