### ISSUE TITLE
Bug: The option to export markdown is missing.

### ISSUE THREAD

**Issue by yuri** [rangle/treillage#9]
The used to have a section that shown raw markdown that could be copied and pasted into the wiki. This is gone now. This feature is the #1 most important feature of the tool, since we cannot publish Rangle Weekly without it. It needs to be restored. Ideally, it would be showing in a separate tab.

**Comment by schoettler** [comment]
Hmmm I now understand the half un-rendered bit of the page. Perhaps we can divide the page vertically and show side to side, the markdown and the rendered version.

**Comment by yuri** [comment]
"Add Markdown to clipboard" button would be a helpful addition, but being able to see the Markdown can be helpful too. I think it would be best to put it in a separate tab. There isn't a lot of need to align it with the rendered version, since those are used at different times.

**Comment by schoettler** [comment]
So 2 buttons, positioned on top (below the tabs) and bottom of the page:

[See Markdown]: Opens a new tab with un-rendered markdown.
[Add Markdown to Clipboard]: Well, does that.

**Comment by yuri** [comment]
That works.

**Comment by yuri** [comment]
Sorry, when I say "tab", I mean a tab within the page, sort of like you currently have "All Cards" and "My Cards". I was thinking we can just add a tab called "Publish", which would show Markdown and have a button at the top to copy Markdown to clipboard.
